name: notes_app
description: "A new Flutter project."
publish_to: 'none' # لمنع النشر العرضي على pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.8.0

flutter:
  uses-material-design: true

  assets:
   

  fonts:
    - family: Schyler
      fonts:
        - asset: lib\fonts\Poppins\Poppins-Regular.ttf
          style: italic

    - family: Trajan Pro
      fonts:
        - asset: lib\fonts\Poppins\Poppins-Regular.ttf
          weight: 700
